on:
  workflow_call:
    inputs:
      image:
        description: The type of machine to run the job on.
        required: false
        type: string
        default: ubuntu-20.04
      mypy-requirements:
        description: Path to additional requirements file necessary for running mypy.
        required: false
        type: string
        default: ""
      python-version:
        description: Version of Python to use.
        required: false
        type: string
        default: "3.10"
      sources-root:
        description: Root directory for your source code.
        required: false
        type: string
        default: "."

jobs:
  pylint:
    runs-on: ${{ inputs.image }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: ${{ inputs.python-version }}

      - name: Cache Python
        id: cache-python
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: py-${{ steps.setup-python.outputs.python-version }}-${{ inputs.image }}

      - name: Cache mypy
        id: cache-mypy
        uses: actions/cache@v3
        with:
          path: .mypy_cache
          key: py-${{ steps.setup-python.outputs.python-version }}-mypy-${{ inputs.image }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install \
            'mypy==0.971' \
            'mypy-extensions==1.0.0' \
            'tomli==2.0.1' \
            'typed-ast==1.5.4' \
            'typing_extensions==4.5.0'

      - name: Install mypy requirements
        run: |
          python -m pip install --requirement ${{ inputs.mypy-requirements }}
        if: ${{ inputs.mypy-requirements != '' }}

      - name: Analysing the code with pylint
        run: |
          mypy --install-types --non-interactive ${{ inputs.sources-root }}
