name: main

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  tox:
    uses: coatl-dev/workflows/.github/workflows/tox.yml@v2.0.1

  pre-commit:
    needs: [tox]
    uses: coatl-dev/workflows/.github/workflows/pre-commit.yml@v2.0.1
    with:
      skip-hooks: pylint

  pylint:
    needs: [tox, pre-commit]
    uses: ./.github/workflows/pylint.yml
