name: main

on:
  workflow_dispatch:
    inputs:
      image:
        description: The type of machine to run the job on.
        required: false
        type: string
        default: ubuntu-20.04
      python-version:
        description: The Python version to install.
        required: false
        type: string
        default: "3.10"
  pull_request:
  push:
    branches:
      - main

jobs:
  tox:
    uses: thecesrom/workflows/.github/workflows/tox.yml@v1.1.1
    with:
      image: ${{ inputs.image }}

  pre-commit:
    needs: tox
    uses: thecesrom/workflows/.github/workflows/pre-commit.yml@v1.1.1
    with:
      image: ${{ inputs.image }}

  pylint:
    needs: [tox, pre-commit]
    runs-on: ${{ inputs.image }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Set Python version
        run: |
          echo "PY=$(python --version)" >> $GITHUB_ENV

      - name: Cache Python
        id: cache-python
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: py-${{ env.PY }}-${{ inputs.image }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pylint

      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
