name: main

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  set-defaults:
    runs-on: ubuntu-20.04
    outputs:
      image: ${{ steps.runner.outputs.image }}
      python-version: ${{ steps.python.outputs.version }}
    steps:
      - name: Set default runner image
        id: runner
        run: |
          echo "image=ubuntu-20.04" >> $GITHUB_OUTPUT

      - name: Set defaul Python version
        id: python
        run: |
          echo "version=3.10" >> $GITHUB_OUTPUT

  tox:
    needs: set-defaults
    uses: thecesrom/workflows/.github/workflows/tox.yml@v1.2.0
    with:
      image: ${{ needs.set-defaults.outputs.image }}

  pre-commit:
    needs: [set-defaults, tox]
    uses: thecesrom/workflows/.github/workflows/pre-commit.yml@v1.2.0
    with:
      image: ${{ needs.set-defaults.outputs.image }}
      skip-hooks: pylint

  pylint:
    needs: [set-defaults, tox, pre-commit]
    runs-on: ${{ needs.set-defaults.outputs.image }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python ${{ needs.set-defaults.outputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ needs.set-defaults.outputs.python-version }}

      - name: Set Python version
        run: |
          echo "PY=$(python --version)" >> $GITHUB_ENV

      - name: Cache Python
        id: cache-python
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: py-${{ env.PY }}-${{ needs.set-defaults.outputs.image }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pylint

      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
