name: main

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  tox:
    uses: thecesrom/workflows/.github/workflows/tox.yml@v1.1.1
    with:
      image: ubuntu-20.04

  pre-commit:
    needs: tox
    uses: thecesrom/workflows/.github/workflows/pre-commit.yml@v1.1.1

  pylint:
    needs: [tox, pre-commit]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set Python version
        run: |
          echo "PY=$(python --version)" >> $GITHUB_ENV

      - name: Cache Python
        id: cache-python
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: py-${{ env.PY }}-${{ inputs.image }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pylint

      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
