name: publish

on:
  release:
    types:
      - published

jobs:
  main:
    uses: coatl-dev/workflows/.github/workflows/pypi-upload.yml@v4.0.1
    secrets:
      pypi-token: ${{ secrets.PYPI_API_TOKEN_IGNITION_API_PKG }}
